### ISSUE TITLE
Two certified Python starter packs fail: python3 and/or xserver box part doesn't include libtk8.5

### ISSUE THREAD

**Issue by confiks** [codio/boxparts#316]
Two of Codio's certified starter packs seem to fail completely because libtk8.5 is missing. I'm not sure which 'box part' should provide it, either python3 or your experimental xserver package. 

Steps to reproduce:

1. Log into Codio account
2. Select 'Starter packs' in left menu
3. Choose 'certified'
4. Choose 'TKinter Clean'
5. In the workspace, execute `python3 demo.py`

Result:
```
Traceback (most recent call last):                                                                                                                                  
  File "demo.py", line 8, in <module>                                                                                                                               
    from tkinter import *                                                                                                                                           
  File "/home/codio/.parts/packages/python3/3.4.3/lib/python3.4/tkinter/__init__.py", line 38, in <module>                                                          
    import _tkinter # If this fails your Python may not be configured for Tk                                                                                        
ImportError: libtk8.5.so.0: cannot open shared object file: No such file or directory
```

**Comment by ijobling** [comment]
Sorry about that, but all sorted.   Create a new project from the starter pack(s) and all should be good again now

**Comment by destitutus** [comment]
No need a new project, just box restart
